import {getService as getServiceProxy} from "adnbn";
import {getService as getServiceOrigin} from "adnbn/service";

import {isBackground} from "@addon-core/browser";

import {normalizeOptions} from "./options";
import {selectConfig} from "./selection";
import {
    PluginName, type RemoteConfig, type RemoteConfigOptions, type RemoteConfigPath, type RemoteConfigValue,
    type ResolvedRemoteConfigOptions,
} from "./types";

export function getRemoteConfig(): Promise<RemoteConfig>;
export function getRemoteConfig<Path extends RemoteConfigPath>(path: Path): Promise<RemoteConfigValue<Path>>;
export function getRemoteConfig<Value>(selector: (config: RemoteConfig) => Value): Promise<Awaited<Value>>;

export async function getRemoteConfig(
    selection?: RemoteConfigPath | ((config: RemoteConfig) => unknown)
): Promise<unknown> {
    const service = isBackground() ? getServiceOrigin : getServiceProxy;

    return selectConfig(await service(`${PluginName}/service`).get(), selection);
}

export const getRemoteConfigOptions = (): ResolvedRemoteConfigOptions => {
    let options: RemoteConfigOptions;

    try {
        //@ts-expect-error: __REMOTE_CONFIG_OPTIONS__ is a virtual variable generated by the bundler `plugin/index.ts`
        options = __REMOTE_CONFIG_OPTIONS__;
    } catch {
        throw new Error(
            `Failed to load ${PluginName} parameters. ` +
            "Make sure the plugin is properly configured in the adnbn configuration file."
        );
    }

    return normalizeOptions(options);
};
