import {getService as getServiceProxy} from "adnbn";
import {getService as getServiceOrigin} from "adnbn/service";

import {isBackground} from "@addon-core/browser";

import {normalizeOptions} from "./options";
import {PluginName, type RemoteConfig, type RemoteConfigOptions, type ResolvedRemoteConfigOptions} from "./types";

export const getRemoteConfig = async <T extends RemoteConfig = RemoteConfig>(): Promise<T> => {
    const service = isBackground() ? getServiceOrigin : getServiceProxy;

    return await service(`${PluginName}/service`).get() as T;
};

export const getRemoteConfigOptions = (): ResolvedRemoteConfigOptions => {
    let options: Partial<RemoteConfigOptions> = {};

    try {
        //@ts-expect-error: __REMOTE_CONFIG_OPTIONS__ is a virtual variable generated by the bundler `plugin/index.ts`
        options = __REMOTE_CONFIG_OPTIONS__;
    } catch {
        console.error(
            `Failed to load ${PluginName} parameters. ` +
            "Make sure the plugin is properly configured in the adnbn configuration file."
        );
    }

    return normalizeOptions(options);
};
